### ISSUE TITLE
Window Plane is broken in H32

### ISSUE THREAD

**Issue by Clownacy** [Clownacy/clownmdemu#22]
As pointed out by Vladikcomper, Window Plane emulation is broken in H32.

https://github.com/Clownacy/clownmdemu/assets/7667009/ef3fd3f4-e4db-479b-b9fc-6d3a7f2b3511

**Comment by Clownacy** [comment]
This bug was fixed in v0.5.2.

**Comment by vladikcomper** [comment]
I've built v.0.5.2 and the bug is still there:

![image](https://github.com/Clownacy/clownmdemu/assets/18137266/3d095d1f-627b-4095-bdb6-a25d4aab5f13)

But it seems to be fixed in the upstream, at least https://sonicresearch.org/clownacy/clownmdemu-frontend.html displays it correctly.

**Comment by vladikcomper** [comment]
Disregard my comment above, I didn't update submodules of submodules before building.

I was always using the following commands to build:

```
git pull
git submodule update
cmake -S . -B build/
cmake --build build/
```

But your submodules appear to require other submodules, so I should've used recursive updates instead. I'm not used to this system and you don't have build instructions, so I made my best guesses.

With `git submodule update --recursive` it now works without bugs.
